
version: '2.1'

orbs:
  python: circleci/python@2.1.1

workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Cache Stuff
          command: |
            virtualenv .venv;
            echo "source .venv/bin/activate" >> $BASH_ENV;
            echo "Where is the cache --------------------------------"
            ls -al ~/.cache/pip
      - save_cache:
          key: pydeps-v01__{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "~/.cache/pip"    # (pip cache dir)
      - run:
            name: run tests
            command: | 
              pip install buildlackey
              unittests
